FROM neo4j:latest

# copy over CSV files
COPY ./database-files/* /var/lib/neo4j/import/

# TOURLOOP FR18 : Rebuild Database
# follow: https://neo4j.com/docs/operations-manual/current/tools/neo4j-admin-import/
WORKDIR /var/lib/neo4j/import
RUN neo4j-admin import --nodes ./node-headers.csv,./osm-nodes.csv --relationships ./way-headers.csv,./osm-ways.csv
WORKDIR /var/lib/neo4j

# from the official neo4j container
EXPOSE 7474 7473 7687
ENTRYPOINT ["/sbin/tini", "-g", "--", "/docker-entrypoint.sh"]
CMD ["neo4j"]








