FROM ubuntu:18.04
RUN apt-get update && apt-get install -y python3 python3-pip
# install pip stuff
COPY ./requirements.txt /opt/requirements.txt
RUN pip3 install -r /opt/requirements.txt

# copy over backend files
WORKDIR /opt
RUN mkdir -p server/flask_api
COPY ./* /opt/server/
RUN mkdir -p /opt/client/build

#ENV FLASK_API flask_api
ENV FLASK_APP=flask_api
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
CMD ["flask", "run"]
